#!/bin/bash
#location of HPL
HPL_DIR=`pwd`

#-------------------module load-------------------------------------

module load cuda/10.1
module load openmpi/openmpi3-x86_64
#module load openmpi/3.1.3-gcc4.8.5
module load intelcompilers/2016.4-compilers

module list

#-------------------------------------------------------------------
export HOSTNAME=`hostname`
echo "HOSTNAME=$HOSTNAME"

DATETIME=`hostname`.`date +"%m%d.%H%M%S"`

echo "Results in ./results/xhpl_4_gpu-$DATETIME-output.txt"

#-------------------------------------------------------------------

nvidia-smi

MPI_WHERE=`which mpirun`
echo "FINDMPI=$MPI_WHERE"

$MPI_WHERE --version

#--------------------run openmpi------------------------------------

##HOSTFILE
#$MPI_WHERE -np 4 --hostfile ./hostfiles/host4_4 -bind-to none -x LD_LIBRARY_PATH ./run_linpack_GPU_1xv100 | tee ./results/xhpl_4_gpu-$DATETIME-output.txt

##RANKFILE
$MPI_WHERE -np 4 --rankfile ./rankfiles/rank4_4 -bind-to none -x LD_LIBRARY_PATH ./run_linpack_GPU_1xv100 | tee ./results/xhpl_4_gpu-$DATETIME-output.txt





